# Generated by Django 5.0.4 on 2024-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_total_alter_uav_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='total',
        ),
        migrations.RemoveField(
            model_name='uav',
            name='price',
        ),
        migrations.AddField(
            model_name='uav',
            name='altitude',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='height',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='length',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='payload_capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
